# Generated by Django 6.0.4 on 2026-05-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Kano State House of Assembly', max_length=255)),
                ('system_name', models.CharField(default='Kano Legislative Digital Management System', max_length=255)),
                ('short_name', models.CharField(default='KLDMS', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('primary_color', models.CharField(default='#0B6B3A', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('accent_color', models.CharField(default='#111827', max_length=20)),
                ('public_hero_title', models.CharField(default='Kano State House of Assembly Public Transparency Portal', max_length=255)),
                ('public_hero_subtitle', models.TextField(default='Access published legislative information, bills, motions, resolutions, sittings, documents, and official public records.')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='Kano Legislative Digital Management System. All rights reserved.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
