# Generated by Django 6.0.4 on 2026-05-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('governor', 'Governor'), ('deputy_governor', 'Deputy Governor'), ('speaker', 'Speaker'), ('deputy_speaker', 'Deputy Speaker'), ('clerk', 'Clerk of the House'), ('deputy_clerk', 'Deputy Clerk'), ('majority_leader', 'Majority Leader'), ('minority_leader', 'Minority Leader'), ('principal_officer', 'Principal Officer'), ('honourable_member', 'Honourable Member'), ('government_official', 'Government Official'), ('former_official', 'Former Official')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='official_photos/')),
                ('short_biography', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('former', 'Former')], default='current', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles', to='constituencies.constituency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_official_profiles', to=settings.AUTH_USER_MODEL)),
                ('political_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles', to='constituencies.politicalparty')),
            ],
            options={
                'ordering': ['display_order', 'category', 'full_name'],
            },
        ),
    ]
