# Generated by Django 6.0.4 on 2026-05-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('speaker', 'Speaker'), ('deputy_speaker', 'Deputy Speaker'), ('clerk', 'Clerk of the House'), ('deputy_clerk', 'Deputy Clerk'), ('committee_clerk', 'Committee Clerk'), ('honourable_member', 'Honourable Member'), ('director_admin_staff', 'Director/Admin Staff'), ('media_pro', 'Media/Public Relations Officer')], default='honourable_member', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('official_title', models.CharField(blank=True, max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
