# Generated by Django 6.0.4 on 2026-05-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislation', '0001_initial'),
        ('members', '0001_initial'),
        ('sittings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vote_number', models.CharField(max_length=100, unique=True)),
                ('vote_type', models.CharField(choices=[('bill', 'Bill'), ('motion', 'Motion'), ('resolution', 'Resolution'), ('other', 'Other Matter')], max_length=30)),
                ('vote_method', models.CharField(choices=[('electronic', 'Electronic Vote'), ('voice', 'Voice Vote'), ('division', 'Division Vote')], default='electronic', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('carried', 'Carried'), ('negatived', 'Negatived'), ('tied', 'Tied')], default='pending', max_length=30)),
                ('decision_summary', models.TextField(blank=True)),
                ('vote_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_sessions', to='legislation.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vote_sessions', to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_sessions', to='legislation.motion')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_sessions', to='legislation.resolution')),
                ('sitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_sessions', to='sittings.plenarysitting')),
            ],
            options={
                'ordering': ['-vote_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='members.honourablemember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='voting.votesession')),
            ],
            options={
                'ordering': ['member__last_name', 'member__first_name'],
                'unique_together': {('session', 'member')},
            },
        ),
    ]
