# Generated by Django 6.0.4 on 2026-05-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlenarySitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sitting_number', models.CharField(max_length=100, unique=True)),
                ('sitting_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(default='Kano State House of Assembly Chamber', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('adjourned', 'Adjourned')], default='scheduled', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sittings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sitting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='order_papers/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_order_papers', to=settings.AUTH_USER_MODEL)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_paper', to='sittings.plenarysitting')),
            ],
        ),
        migrations.CreateModel(
            name='HansardTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transcript', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='hansards/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_hansards', to=settings.AUTH_USER_MODEL)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hansard', to='sittings.plenarysitting')),
            ],
        ),
        migrations.CreateModel(
            name='SittingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('presenter', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='sittings.plenarysitting')),
            ],
            options={
                'ordering': ['order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SittingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='sitting_documents/')),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sittings.plenarysitting')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VotesProceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='votes_proceedings/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_votes_proceedings', to=settings.AUTH_USER_MODEL)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votes_proceeding', to='sittings.plenarysitting')),
            ],
        ),
    ]
