# Generated by Django 6.0.4 on 2026-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
