# Generated by Django 6.0.4 on 2026-05-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_device_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('search', 'Search'), ('download', 'Download'), ('permission_denied', 'Permission Denied'), ('suspicious', 'Suspicious Activity')], max_length=50),
        ),
    ]
